# Emit aligned native uint32_t words from little-endian SPIR-V, without Python.
file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" length)
math(EXPR remainder "${length} % 8")
if(NOT remainder EQUAL 0 OR length EQUAL 0)
  message(FATAL_ERROR "Invalid SPIR-V length: ${INPUT}")
endif()
set(text "// Generated from GLSL by glslc.\nstatic const uint32_t ${SYMBOL}[] = {\n")
math(EXPR last "${length} - 8")
foreach(i RANGE 0 ${last} 8)
  string(SUBSTRING "${hex}" ${i} 8 word)
  string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," word "${word}")
  string(APPEND text "${word}\n")
endforeach()
string(APPEND text "};\n")
file(WRITE "${OUTPUT}" "${text}")
